### ISSUE TITLE
Include dendrite in sandbox 

### ISSUE THREAD

**Issue by ashfame** [Automattic/matrix-env#8]
Choose a different docker compose file, which when chosen, uses dendrite instead of synapse for provisioning the sandbox.

**Comment by psrpinto** [comment]
This makes sense. So that other services work with either dendrite or synapse, one strategy would be to set the hostname of both the synapse and dendrite containers to e.g. `matrix-env-homeserver`. Then services can reference that hostname instead of `matrix-env-synapse`, as is the case today. Not sure that won't have unexpected side-effects though, I guess we need to try it out and see.

**Comment by akirk** [comment]
See #9
